<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="AddStep" Id="{a405a588-ce74-42a1-baa6-b3e398d6c40f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION AddStep : bool
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="AddStep">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>