<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Next" Id="{d3b22c90-bd98-4859-b303-dabbf9611a0d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Next 
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[G_Match.iEtapeAction := G_Match.iEtapeAction + 1;]]></ST>
    </Implementation>
    <LineIds Name="Next">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>