<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ReplaceStep" Id="{a91df4fa-cd8a-488c-8cb8-ec84394d75a6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION ReplaceStep : bool
VAR_INPUT
	step:ST_Tableau;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//change l'étape actuelle
G_Match.Tableau[G_Match.iLigne] := step;]]></ST>
    </Implementation>
    <LineIds Name="ReplaceStep">
      <LineId Id="15" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>