<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="DEGRE2RAD" Id="{1d2279b9-2f42-4930-995a-c27356d14dd3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION DEGRE2RAD : lreal
VAR_INPUT
	lrAngle : LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[DEGRE2RAD := lrAngle*PI/180;]]></ST>
    </Implementation>
    <LineIds Name="DEGRE2RAD">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>